### ISSUE TITLE
Server crash when using base_image 'ubuntu'

### ISSUE THREAD

**Issue by tyzess** [lunactic/DIVAServices#11]
Wanted to check how DIVAAlgorithms (and DIVAService aswell) react on a false base image. Feeded the 'ubuntu' base image to the otherwise correct cannyedgedetection algorithm. Tested with clean environment and preloaded ubuntu:latest image.

```
{"stream":" ---\u003e 44776f55294a\n"}
^

SyntaxError: Unexpected token {
  at Object.parse (native)
  at IncomingMessage.<anonymous> (/home/lunactic/DEV/DIVAServices_Node/app/docker/dockerManagement.js:52:27)
  at emitOne (events.js:77:13)
  at IncomingMessage.emit (events.js:169:7)
  at IncomingMessage.Readable.read (_stream_readable.js:360:10)
  at flow (_stream_readable.js:743:26)
  at resume_ (_stream_readable.js:723:3)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)

```

**Comment by lunactic** [comment]
@uzysset I think this should be solved with cad4ca9
This should result in the status of the algorithm to become 500 could you test that?

**Comment by tyzess** [comment]
@lunactic Can't deploy a fully correct 'cannyedgedetector' algorithm anymore (newest commit):

DIVAService:
`[2016-04-29 18:50:26.502] [INFO] server - HTTP Server listening on port 8080
[2016-04-29 19:00:42.386] [INFO] server - successfully built the image
[2016-04-29 19:00:42.705] [INFO] server - ./script.sh http://localhost:8080/static/generalpowderbluedrake/original/input0.png http://172.17.0.1:8080/jobs/482bqpn8nxdjwcdi
[2016-04-29 19:00:42.708] [INFO] server - { results: [ { resultLink: 'http://localhost:8080/OCR/cannyedgedetection?md5=4adddfaa693b184d675d61d21efda43c' } ],
  collection: 'generalpowderbluedrake',
  resultLink: 'http://localhost:8080/OCR/cannyedgedetection?collection=generalpowderbluedrake',
  status: 'done' }
/home/lunactic/DEV/DIVAServices_Node/app/management/algorithmManagement.js:53
          currentInfo.status.statusCode = 200;
                                        ^

TypeError: Cannot set property 'statusCode' of undefined
  at Function.module.exports.AlgorithmManagement.updateStatus (/home/lunactic/DEV/DIVAServices_Node/app/management/algorithmManagement.js:53:41)
  at /home/lunactic/DEV/DIVAServices_Node/app/routes/router.js:104:33
  at Object.schemaValidator.validate (/home/lunactic/DEV/DIVAServices_Node/app/validator/schemaValidator.js:24:14)
  at /home/lunactic/DEV/DIVAServices_Node/app/routes/router.js:99:32
  at /home/lunactic/DEV/DIVAServices_Node/node_modules/async/dist/async.js:365:16
  at nextTask (/home/lunactic/DEV/DIVAServices_Node/node_modules/async/dist/async.js:3908:27)
  at /home/lunactic/DEV/DIVAServices_Node/node_modules/async/dist/async.js:3915:17
  at /home/lunactic/DEV/DIVAServices_Node/node_modules/async/dist/async.js:307:31
  at /home/lunactic/DEV/DIVAServices_Node/node_modules/async/dist/async.js:804:16
  at /home/lunactic/DEV/DIVAServices_Node/app/routes/router.js:88:13
  at /home/lunactic/DEV/DIVAServices_Node/app/helper/resultHandlers/fileResultHandler.js:55:22
  at tryToString (fs.js:414:3)
  at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:401:12)
`

Docker:
`CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS                           PORTS               NAMES
1c30baf3f54c        canny_edge_detection   "bash -c './script.sh"   About a minute ago   Exited (52) About a minute ago                       serene_cray
`
DIVAAlgorithm will timeout I guess

**Comment by lunactic** [comment]
@uzysset Can I close this issue? I don't think it exsists anymore.
