### ISSUE TITLE
Invalid JSON on API kills DIVAServices via Parser

### ISSUE THREAD

**Issue by tyzess** [lunactic/DIVAServices#26]
### Example

POST /algorithms/
Body: { . }

**DIVAServices crashes!**
SyntaxError: Unexpected token .
  at Object.parse (native)
  at parse (/home/lunactic/DEV/DIVAServices_Node/node_modules/body-parser/lib/types/json.js:88:17)
  at /home/lunactic/DEV/DIVAServices_Node/node_modules/body-parser/lib/read.js:116:18
  at invokeCallback (/home/lunactic/DEV/DIVAServices_Node/node_modules/raw-body/index.js:262:16)
  at done (/home/lunactic/DEV/DIVAServices_Node/node_modules/raw-body/index.js:251:7)
  at IncomingMessage.onEnd (/home/lunactic/DEV/DIVAServices_Node/node_modules/raw-body/index.js:308:7)
  at emitNone (events.js:67:13)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)

**Comment by tyzess** [comment]
Same url with body: 

```
{ 

    "general":  {
        "name": "Test",
        "description": "dsffff",
        "author": "test",
        "type": "dsfds",
        "email": "33@dsfdsf.cd"
    },
    "input": [


    ],
    "output": {
        "output_type": "dsf"

    },
    "method": {
        "file": "https://www.google.ch",
        "environment": "ddsfdd",
        "executableType": "dsfs33",
        "executable_path": "dsfdsf"

    }
}
```

**DIVAServices crashes!**
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '/data/executables/dsfds/test/'
  at Error (native)

**Comment by lunactic** [comment]
I implemented two fixes:
- 8a23135 adds an additional check with a HTTP HEAD request to ensure the passed files is a zip file
- 77b1954 adds proper error handling for invalid JSON
